wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681313262.221834
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 9
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 1
      - 5
